### ISSUE TITLE
Update assembly info better

### ISSUE THREAD

**Issue by AlenPelin** [AlenPelin/GitHubReleaseDaemonNet#1]
Currently assembly info file is being updated with version attributes only if they are missing. We need to completely rewrite assembly info and project properties:
* AssemblyTitle = AssemblyProduct = GitHub repository name
* AssemblyDescription = GitHub repository description
* AssemblyCopyright = Copyright © Sitecore 2016
* AssemblyVersion = AssemblyFileVersion = AssemblyInformationalVersion = Tag name

**Comment by AlenPelin** [comment]
@RomanChernyk @olegburov @ivansharamok @andrew-at-sitecore your thoughts on that?

**Comment by olegburov** [comment]
+1
Sounds good to me.
